parameters:
#    cf_front.example.class: CF\FrontBundle\Example

services:
#    cf_front.example:
#        class: %cf_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
